### PR TITLE
fix codeblock collapse bug

### LINKED ISSUE #280: [Bug] Code block max lines regression
**I have checked all the prerequisites below and I'm yet experiencing a problem**

- [x] Read the README.md
- [x] Have the extended version of Hugo installed
- [x] Used the exampleSite's config.toml as a reference
- [x] I have included my repository link. Instead of pasting long snippets here.

**Describe the bug**

In a recent commit, the code block max lines isn't being obeyed.
From [here](https://neonmirrors.net/post/2021-06/policy-k8s-customresources/).

Correct:

image

Incorrect:

image

Also note the elipses (three dots) at the bottom of the fully expanded code block in the incorrect screenshot. These should not be visible when a code block is fully extended.

### PR DESCRIPTION
**Pull request by onweru**
This PR...

## Changes / fixes

- fixes #280 

## Screenshots (if applicable)

https://user-images.githubusercontent.com/16350351/168332593-14046b3e-0816-4079-8448-3f0d3610729a.mov

## Checklist

_Ensure you have checked off the following before submitting your PR._

- [x] tested locally with the [latest release of Hugo](https://github.com/gohugoio/hugo/releases). This requirement is [a standard](https://github.com/gohugoio/hugoThemes#theme-maintenance)
- [ ] added new dependencies
- [ ] updated the [docs]() ⚠️

### CODE REVIEW

**Review by chipzoller — APPROVED** [review]

**Review by rootwork — APPROVED** [review]

File: assets/js/code.js [hunk 1]
```diff
@@ -177,7 +177,7 @@ function copyCode(codeElement) {
 }
 
 function disableCodeLineNumbers(block){
-  const lines = elems('.ln', block)
+  const lines = elems(lineClass, block)
```
Comment (onweru) [inline assets/js/code.js:180]: This is the regression introduced and fixed in #312 & #315
